# Site settings
title: Blog da Imagem Cardíaca
header-img: img/home-bg.jpg
description: "Temas em imagem cardíaca."
baseurl: "/startbootstrap-clean-blog-jekyll"
url: "http://bernardobap.github.io"

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 3
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
